### ISSUE TITLE
setInvoiceId ve line

### ISSUE THREAD

**Issue by sercanaydin** [sportakal/digitalplanet#1]
Merhaba,
Fatura numarasını her defasında biz mi belirlememiz gerekiyor bunun takibi bizde mi olacak.
Yoksa başka bir method mevcut mudur ? Teşekkürler kolay gelsin.

$invoiceInfo->setInvoiceId(time());

Birde tek satır fatura kalemi mi ekleyebiliyoruz loopa aldığımda diğer itemler fatura satırlarına eklenmiyor.

**Comment by sportakal** [comment]
Merhaba,

`$invoiceInfo->setInvoiceId(time());`
Bu method faturanıza kendi uniq id'nizi belirlemenize yarıyor. Faturadaki resmi Fatura No'su otomatik olarak oluşturuluyor.

Sıradaki fatura no'sunu öğrenebilmeniz için **GetNewInvoiceId** diye bir method bulunuyor. Ancak zorunlu değil.

**Comment by sportakal** [comment]
Birden fazla satır eklemeyi denememiştim. Kontrol ediyorum, hatayı bulup fixleyeceğim.

**Comment by sportakal** [comment]
@sercanaydin

Bir kaç tane hatayı çözdüm. 1.0.4 sürümüne güncelleyerek yeniden dener misin?

samples klasöründeki aşağıdaki istekte denedim.

https://github.com/sportakal/digitalplanet/blob/main/samples/sendEArchiveData.php

`$invoiceLines->setLine($line1);`
`$invoiceLines->setLine($line2);`
`$invoiceLines->setLine($line3);`


Hala hata alırsan, içeriğini paylaşmanı rica ediyorum.
