### ISSUE TITLE
Fatura altı matrah

### ISSUE THREAD

**Issue by pokp** [sportakal/digitalplanet#2]
Fatura altı 8/18 kdv matrahlarını nasıl taxtotals methoduna ekleyebilirim? Dökümanda tek tip kdv gösterilmiş iki ayrı kdv gösterilmemiş. Teşekkürler

**Comment by sportakal** [comment]
Fatura altında, farklı oranları yazmanıza gerek olmayabilir. Her satırdaki farklı KDV tutarlarının toplamını girmek yeterli olacaktır. Boş bırakmayı denediniz mi, bir hata oluşuyor mu?

Ortalama oran yazmayı da deneyebilirsiniz. 
`$taxesTaxSubTotals->setPercent(18);`
methodu basılan faturada görünmüyor olmalıdır. Ortalama oran yazılmasının bir sakıncası olmayacaktır.

Bunları denediğinizde, bir hata alıyor musunuz?

**Comment by pokp** [comment]
Çok teşekkür ederim 2 gündür bununla uğraştım nerde hata yapıyorum diye 😄 taxes methodunu göndermemek en mantıklısıymış digitalplanet kendisi hesaplayıp ekliyormuş tekrar teşekkürler 🙏
